export * from './event-list.component' 
export * from './event-list-resolved.service'
export * from './event-resolver.service'
export * from './events.component' 
export * from './shared/index' 
export * from './events-detail/index' 
export * from './shared/duration.pipe'
export * from './location-validator.directive'